feat(JOML): cleanup and migrate to joml
Terasology/Scenario pull request #48
Opened 2020-10-17 18:48 UTC by pollend

2020-11-04 23:07 UTC, jdrueckert approved these changes, later dismissed

2020-12-31 12:00 UTC, skaldarnar commented
For some reason the github diff view is totally off 🙈 Hard to review `+1,304 −1,312` when most of the time only a few imports have changed... 🙄

2020-12-31 17:45 UTC, pollend commented
> For some reason the github diff view is totally off see_no_evil Hard to review `+1,304 −1,312` when most of the time only a few imports have changed... roll_eyes

hiding the spacing helps quite a bit. I could drop the formatting and just do it in another PR.

2021-01-02 16:39 UTC, skaldarnar requested changes
The tip with hiding white space changes was really helpful, brought this changeset down to `+124 −132` 👍

2021-01-02 16:39 UTC, skaldarnar commented on src/main/java/org/terasology/scenario/internal/systems/RegionSystem.java
> +                            loc.region = new BlockRegion(pos, create.firstHit);//Region3i.createBounded(pos, create.firstHit);
I think the equivalent to `createBounded` is to build the union of those two positions.
```suggestion
                            loc.region = new BlockRegion(pos).union(create.firstHit);
```

2021-01-02 16:39 UTC, skaldarnar commented on src/main/java/org/terasology/scenario/internal/systems/RegionTreeSystem.java
> +        // Scenario
```suggestion
		// Checks for existing scenarios
        Iterable<EntityRef> scenario = entityManager.getEntitiesWith(ScenarioComponent.class); 
```

2021-01-02 16:40 UTC, skaldarnar approved these changes

2021-01-02 16:46 UTC, merged